### ISSUE TITLE
Widget与provider结合是不是就不需要使用StatefulWidget

### ISSUE THREAD

**Issue by zouxianbincc** [ditclear/mvvm_flutter#3]
我有个疑问，使了provider后，不需要使用StatefulWidget，就能对界面数据进行刷新，如何控制好粒度，是不是可以提高性能，相比StatefulWidget而言。
我这种想法不知道对不对，望赐教。
如果不用StatefulWidget，而用provider代替刷新界面，又该如何封装呢？

**Comment by ditclear** [comment]
@zouxianbincc
StatefulWidget和provider所属分工并不一样，StatefulWidget是用来创建widget的，不止包括使用setState来更新数据，还有动画等等其它的

而provider是一个状态管理框架，是用于减少setState导致的性能开销，并不提供创建widget的功能
二者并不一样
