### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by ToZhanChi** [ditclear/mvvm_flutter#4]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\BC\Projects\Flutter\Flutter_zzzzzzzzzzzzzzz\mvvm_flutter-master\android\app\build.gradle' line: 26

* What went wrong:
A problem occurred evaluating project ':app'.
> D:\BC\Projects\Flutter\Flutter_zzzzzzzzzzzzzzz\mvvm_flutter-master\android\key.properties (ϵͳ�Ҳ���ָ�����ļ���)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by ditclear** [comment]
@zhanchi88 少了一个key.properties，我最近升级一下环境，更新一个版本。也可以先跑跑web或者ios版本

**Comment by ditclear** [comment]
有时间升级了一下版本，可以再拉下代码试一试 @zhanchi88
